openapi: 3.1.0
components:
  schemas:
    DeleteUpload:
      type: object
      properties:
        filename:
          type: string
          default: file destination 
        id:
          type: string
          default: user id
