openapi: 3.1.0
components:
   schemas:
    UserInput:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          default: zudskyy
        password:
          type: string
          default: 1234
