openapi: 3.1.0
info:
  title: Login
  version: 1.0.0
paths:
  /login:
    post:
      tags:
        - Login
      summary: Register a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  username:
                    type: string
                  email: 
                    type: string
                  files:
                    type: array
                  accessToken:
                    type: string
        '409':
          description: Conflict
        '500':
          description: Server Error      