openapi: 3.1.0
components:
  schemas:
    UploadInput:
      type: object
      properties:
        id:
          type: string
          default: user id
        files:
          type: array
          items:
            type: string
            format: binary
